root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ./cmd/server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "testdata"]
  exclude_regex = ["_test.go"]
  log = "build-errors.log"

[color]
  main = "magenta"
  build = "yellow"
  runner = "green"
  watcher = "cyan"

[screen]
  keep_scroll = true