// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/edynt/go-ecommerce-api/internal/controllers"
	"github.com/edynt/go-ecommerce-api/internal/repo"
	"github.com/edynt/go-ecommerce-api/internal/services"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controllers.UserController, error) {
	iUuserRepository := repo.NewUserRepository()
	iUserService := services.NewUserService(iUuserRepository)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}
