server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: shopdevgo
  maxIdleConns: 10 # max pull connect
  maxOpenConns: 100 #dat so luong ket noi toi da co the
  connMaxLifetime: 3600 #thoi gian ket noi toi da