server:
  port: 8080
  mode: "development"
mysql:
  host: 127.0.0.1 #mysql_container
  port: 3306
  username: root
  password: root
  database: shopdev
  maxIdleConns: 10 # max pull connect
  maxOpenConns: 100 #dat so luong ket noi toi da co the
  connMaxLifetime: 3600 #thoi gian ket noi toi da
logger:
  log_level: debug
  file_log_name: "./storage/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: 127.0.0.1 #redis_container
  port: 6379
  password:
  database: 0